name: CICD-SSH
on:
  push:
      branches: [ main ]
      paths:
        - 'part2/04-cicd/**'
        - '.github/workflows/deploy_ssh.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            ls -a
            cd ~/${{ github.event.repository.name }}/part2/04-cicd
            sh deploy_ssh.sh
